#!/bin/zsh
# @file      cat_all_files
# @author    Ignacio Vizzo     [ivizzo@uni-bonn.de
#
# Copyright (c) 2019 Ignacio Vizzo, all rights reserved
source $ZSH/custom/load_colors.zsh

for source in *; do
  echo "${BOLD_YELLOW}$source:${RESET}"
  cat $source && echo
done
