#!/usr/bin/env zsh
# @author    Ignacio Vizzo     [ivizzo@uni-bonn.de]
#
# Copyright (c) 2019 Ignacio Vizzo, all rights reserved
source $VIRTUALENV/open3d_headless/bin/activate
python3 $HOME/scripts/visualize_ply.py --headless ${@}
